apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aad-pod-identity

resources:
- namespace.yaml
- https://github.com/Azure/aad-pod-identity/releases/download/v1.8.5/deployment-rbac.yaml
- https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/mic-exception.yaml

replicas:
- name: mic
  count: 1
